// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportHTMLReport():Promise<string>;

export function ExportHTMLTreeReport():Promise<string>;

export function GetFolderView(arg1:string):Promise<main.FolderView>;

export function GetRootFolderView():Promise<main.FolderView>;

export function SelectDirectory(arg1:string):Promise<string>;
