// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportHTMLReport() {
  return window['go']['main']['App']['ExportHTMLReport']();
}

export function ExportHTMLTreeReport() {
  return window['go']['main']['App']['ExportHTMLTreeReport']();
}

export function ExportRawDataCSV() {
  return window['go']['main']['App']['ExportRawDataCSV']();
}

export function ExportTextTreeReport() {
  return window['go']['main']['App']['ExportTextTreeReport']();
}

export function GetFolderView(arg1) {
  return window['go']['main']['App']['GetFolderView'](arg1);
}

export function GetRootFolderView() {
  return window['go']['main']['App']['GetRootFolderView']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}
